name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install pipenv
        pipenv sync --dev
    - name: Analysing the code with pylint
      run: |
        pipenv run pylint $(git ls-files '*.py')
    - name: Run tests
      run: |
        pipenv run pytest src/
